"""Compile study_guides/anchors.yaml into anchors.tex macros.

The IDs-not-text contract (plan 012 R1): documents write ``\\anchor{key}``
and the build splices the verified value; a human or agent never retypes a
digit. This script is deterministic — same yaml, same tex — so the generated
file is committed and tests can assert it is in sync.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
YAML_PATH = ROOT / "study_guides" / "anchors.yaml"
TEX_PATH = ROOT / "study_guides" / "anchors.tex"

HEADER = (
    "% Generated by tools/build_anchors.py from anchors.yaml — do not edit.\n"
    "% Each macro splices a verified value; the cited plan anchor is the\n"
    "% argument of record.\n"
)


def render(entries: dict) -> str:
    lines = [HEADER]
    for key in sorted(entries):
        meta = entries[key]
        value = meta["value"]
        source = meta.get("source", "unsourced")
        lines.append(f"% {key}: {meta.get('description', '')} [{source}]")
        lines.append(f"\\expandafter\\newcommand\\csname anchor@{key}\\endcsname{{{value}}}")
    return "\n".join(lines) + "\n"


def main() -> int:
    entries = yaml.safe_load(YAML_PATH.read_text(encoding="utf-8"))
    missing = [k for k, m in entries.items() if "value" not in m or "source" not in m]
    if missing:
        print(f"anchors.yaml entries missing value/source: {missing}", file=sys.stderr)
        return 1
    TEX_PATH.write_text(render(entries), encoding="utf-8")
    print(f"wrote {TEX_PATH.relative_to(ROOT)} ({len(entries)} anchors)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
