"""Sync the human-ticked README reference lists into references.bib.

The markdown checklists stay the source of truth — ticks are the
maintainer's alone (CLAUDE.md), and this script never writes markdown. It
reads every topic README's References section and emits one deterministic
``study_guides/references.bib`` whose entries carry ``verified = {yes|no}``
from the tick state (plan 012 R5). Guides cite by key; biblatex prints only
what a document actually cites.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BIB_PATH = ROOT / "study_guides" / "references.bib"

ENTRY = re.compile(r"^- \[( |X|x)\] \[(?P<title>.+?)\]\((?P<url>\S+?)\)")

HEADER = (
    "% Generated by tools/sync_references.py from the topic READMEs'\n"
    "% human-gated reference lists — do not edit. verified={yes} means the\n"
    "% maintainer opened, confirmed, and ticked the entry; verified={no}\n"
    "% entries are a to-do, and citing one requires an on-page unverified\n"
    "% mark.\n"
)


def slugify(title: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return slug[:60].rstrip("-")


def collect() -> dict[str, dict]:
    entries: dict[str, dict] = {}
    for readme in sorted(ROOT.glob("*/README.md")):
        topic = readme.parent.name
        in_refs = False
        for line in readme.read_text(encoding="utf-8").splitlines():
            if line.startswith("## "):
                in_refs = line.strip() == "## References"
                continue
            if not in_refs:
                continue
            match = ENTRY.match(line)
            if not match:
                continue
            verified = "yes" if match.group(1) in "Xx" else "no"
            title = match.group("title")
            key = f"{topic}-{slugify(title)}"
            entries[key] = {
                "title": title,
                "url": match.group("url"),
                "verified": verified,
                "topic": topic,
            }
    return entries


def render(entries: dict[str, dict]) -> str:
    blocks = [HEADER]
    for key in sorted(entries):
        meta = entries[key]
        title = meta["title"].replace("&", "\\&")
        blocks.append(
            f"@misc{{{key},\n"
            f"  title = {{{{{title}}}}},\n"
            f"  howpublished = {{\\url{{{meta['url']}}}}},\n"
            f"  note = {{via {meta['topic']}/README.md}},\n"
            f"  verified = {{{meta['verified']}}},\n"
            f"}}"
        )
    return "\n\n".join(blocks) + "\n"


def main() -> int:
    entries = collect()
    BIB_PATH.write_text(render(entries), encoding="utf-8")
    ticked = sum(1 for m in entries.values() if m["verified"] == "yes")
    print(f"wrote {BIB_PATH.relative_to(ROOT)}: {len(entries)} entries, {ticked} verified")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
